#!/bin/bash -u

# Script assumes file fits n.3 convention, so check that the filename is
# OK before proceeding.
if [[ ${1: -4} != ".tex" ]]; then
    echo "Script requires a .tex file!"
    exit 1
fi

# Check source file is accessable.
if [[ -f $1 ]]; then
    echo [ $(date +%H:%M:%S) ] Using file $1
else
    echo "File does't exist!"
    exit 1
fi

# Create a temp directory to hold all of the stuff
workdir=$(mktemp -d)

echo Working in ${workdir}

# Startup message.
echo [ $(date +%H:%M:%S) ] latexter started.

# Set lastmod to 0 so that we always render on launch.
lastmod=0
# Flag to decide if we should open the pdf.
opened=0

function compile {
        pdflatex -halt-on-error -shell-escape -interaction=nonstopmode \
        -file-line-error -output-directory $1 $2 | tail -n 10
        texcount $2
}

while true; do
    # Get last modifcaion of source.
    mod=$(stat -c %Y ${1})
    # Check if the file has been modified.
    if [[ mod -gt lastmod ]]; then
        # Copy the source, and tell minted to work in this directory.
        sed "s|__OUTPUTDIR__|outputdir=${workdir}|g" ${1} > ${workdir}/${1}
        echo [ $(date +%H:%M:%S) ] Generating PDF.
        compile ${workdir} ${1}
        # Open the PDF if it hasn't been opened, and is available.
        if [[ opened -eq 0 && -r ${workdir}/${1:0:-4}.pdf ]]
        then
            # Rebuild for object references.
            compile ${workdir} ${1}
            xdg-open ${workdir}/${1:0:-4}.pdf > /dev/null 2>&1 &
            opened=1
        fi
        if [[ -r ${workdir}/${1:0:-4}.pdf ]]; then
            env DISPLAY=":0.0" paplay /usr/share/sounds/freedesktop/stereo/message.oga
            cp ${workdir}/${1:0:-4}.pdf .
            echo [ $(date +%H:%M:%S) ] Done!
        else
            env DISPLAY=":0.0" paplay /usr/share/sounds/freedesktop/stereo/bell.oga
            echo [ $(date +%H:%M:%S) ] Compilation Failed with Error:
            cat ${workdir}/${1:0:-4}.log | grep -A 2 "${workdir}/${1}:.*:"
        fi
    fi
    lastmod=${mod}
    sleep 1
done
